# Generated by Django 5.2.1 on 2025-05-17 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roommaterequests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roommaterequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Declined', 'Declined'), ('Cancelled', 'Cancelled')], default='pending', max_length=10),
        ),
    ]
