# Generated by Django 5.2.1 on 2025-05-14 17:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('User', 'User'), ('Admin', 'Admin')], default='User', max_length=20)),
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('prefer_not_to_say', 'Prefer not to say')], max_length=20, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('sleep_schedule', models.CharField(blank=True, choices=[('early_bird', 'Early Bird'), ('night_owl', 'Night Owl'), ('flexible', 'Flexible')], max_length=20, null=True)),
                ('cleanliness_level', models.CharField(blank=True, choices=[('neat', 'Neat'), ('average', 'Average'), ('messy', 'Messy')], max_length=20, null=True)),
                ('social_habits', models.CharField(blank=True, choices=[('introvert', 'Introvert'), ('extrovert', 'Extrovert'), ('ambivert', 'Ambivert')], max_length=20, null=True)),
                ('study_preference', models.CharField(blank=True, choices=[('quiet', 'Quiet and private'), ('group', 'Group study'), ('mixed', 'Mixed')], max_length=20, null=True)),
                ('hobbies', models.TextField(blank=True, null=True)),
                ('interests', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
