# Generated by Django 5.2.1 on 2025-05-21 13:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('User', 'User'), ('Admin', 'Admin')], default='User', max_length=20)),
                ('verification_status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='pending', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other'), ('Prefer not to say', 'Prefer not to say')], max_length=20, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('sleep_schedule', models.CharField(blank=True, choices=[('Early Bird', 'Early Bird'), ('Night Owl', 'Night Owl'), ('Flexible', 'Flexible')], max_length=20, null=True)),
                ('cleanliness_level', models.CharField(blank=True, choices=[('Neat', 'Neat'), ('Average', 'Average'), ('Messy', 'Messy')], max_length=20, null=True)),
                ('social_habits', models.CharField(blank=True, choices=[('Introvert', 'Introvert'), ('Extrovert', 'Extrovert'), ('Ambivert', 'Ambivert')], max_length=20, null=True)),
                ('study_preference', models.CharField(blank=True, choices=[('Quiet', 'Quiet and private'), ('Group', 'Group study'), ('Mixed', 'Mixed')], max_length=20, null=True)),
                ('noise_tolerance', models.CharField(blank=True, choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=20, null=True)),
                ('cooking_frequency', models.CharField(blank=True, choices=[('Rarely', 'Rarely'), ('Sometimes', 'Sometimes'), ('Frequently', 'Frequently')], max_length=20, null=True)),
                ('guest_policy', models.CharField(blank=True, choices=[('Never', 'Never'), ('Sometimes', 'Sometimes'), ('Often', 'Often')], max_length=20, null=True)),
                ('pet_preference', models.CharField(blank=True, choices=[('No pets', 'No pets'), ('Okay with pets', 'Okay with pets'), ('Have pets', 'Have pets')], max_length=20, null=True)),
                ('smoking_preference', models.CharField(blank=True, choices=[('Non-smoker', 'Non-smoker'), ('Okay with smoking', 'Okay with smoking'), ('Smoker', 'Smoker')], max_length=20, null=True)),
                ('hobbies', models.TextField(blank=True, null=True)),
                ('interests', models.TextField(blank=True, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='media/profile_pictures/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
