# Generated by Django 5.2.1 on 2025-05-19 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cooking_frequency',
            field=models.CharField(blank=True, choices=[('rarely', 'Rarely'), ('sometimes', 'Sometimes'), ('frequently', 'Frequently')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='guest_policy',
            field=models.CharField(blank=True, choices=[('never', 'Never'), ('sometimes', 'Sometimes'), ('often', 'Often')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='noise_tolerance',
            field=models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='pet_preference',
            field=models.CharField(blank=True, choices=[('no_pets', 'No pets'), ('ok_with_pets', 'Okay with pets'), ('have_pets', 'Have pets')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='smoking_preference',
            field=models.CharField(blank=True, choices=[('non_smoker', 'Non-smoker'), ('ok_with_smoking', 'Okay with smoking'), ('smoker', 'Smoker')], max_length=20, null=True),
        ),
    ]
