# Generated by Django 5.2.1 on 2025-05-19 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_cooking_frequency_profile_guest_policy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('Prefer not to say', 'Prefer not to say')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pet_preference',
            field=models.CharField(blank=True, choices=[('No pets', 'No pets'), ('Okay with pets', 'Okay with pets'), ('Have pets', 'Have pets')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='smoking_preference',
            field=models.CharField(blank=True, choices=[('Non-smoker', 'Non-smoker'), ('Okay with smoking', 'Okay with smoking'), ('smoker', 'Smoker')], max_length=20, null=True),
        ),
    ]
