# Generated by Django 5.2.1 on 2025-05-19 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_profile_gender_alter_profile_pet_preference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cleanliness_level',
            field=models.CharField(blank=True, choices=[('Neat', 'Neat'), ('Average', 'Average'), ('Messy', 'Messy')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cooking_frequency',
            field=models.CharField(blank=True, choices=[('Rarely', 'Rarely'), ('Sometimes', 'Sometimes'), ('Frequently', 'Frequently')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other'), ('Prefer not to say', 'Prefer not to say')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='guest_policy',
            field=models.CharField(blank=True, choices=[('Never', 'Never'), ('Sometimes', 'Sometimes'), ('Often', 'Often')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='noise_tolerance',
            field=models.CharField(blank=True, choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sleep_schedule',
            field=models.CharField(blank=True, choices=[('Early Bird', 'Early Bird'), ('Night Owl', 'Night Owl'), ('Flexible', 'Flexible')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='smoking_preference',
            field=models.CharField(blank=True, choices=[('Non-smoker', 'Non-smoker'), ('Okay with smoking', 'Okay with smoking'), ('Smoker', 'Smoker')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='social_habits',
            field=models.CharField(blank=True, choices=[('Introvert', 'Introvert'), ('Extrovert', 'Extrovert'), ('Ambivert', 'Ambivert')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='study_preference',
            field=models.CharField(blank=True, choices=[('Quiet', 'Quiet and private'), ('Group', 'Group study'), ('Mixed', 'Mixed')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='verification_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
