# Generated by Django 5.2.1 on 2025-05-18 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionaire', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='created_at',
            new_name='created',
        ),
    ]
